// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: vDNSJ6umd6G
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicMcserverProxy.module.css"; // plasmic-import: vDNSJ6umd6G/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon
import DownloadIcon143099SvgIcon from "./icons/PlasmicIcon__DownloadIcon143099Svg"; // plasmic-import: -1dlLAmHP/icon

export type PlasmicMcserverProxy__VariantMembers = {};

export type PlasmicMcserverProxy__VariantsArgs = {};
type VariantPropType = keyof PlasmicMcserverProxy__VariantsArgs;
export const PlasmicMcserverProxy__VariantProps = new Array<VariantPropType>();

export type PlasmicMcserverProxy__ArgsType = {};
type ArgPropType = keyof PlasmicMcserverProxy__ArgsType;
export const PlasmicMcserverProxy__ArgProps = new Array<ArgPropType>();

export type PlasmicMcserverProxy__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMcserverProxyProps {}

function PlasmicMcserverProxy__RenderFunc(props: {
  variants: PlasmicMcserverProxy__VariantsArgs;
  args: PlasmicMcserverProxy__ArgsType;
  overrides: PlasmicMcserverProxy__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <title key="title">{"PROXY SERVER"}</title>

        <meta key="og:title" property="og:title" content={"PROXY SERVER"} />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={"PROXY SERVER"}
        />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal__phzcp)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__vVHq)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("blue" as const)
                  : ("blue" as const)
              }
              link={"/" as const}
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eDtbO
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__zwmsS)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__rzXbB)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yhedK
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PLATZ 1\nVELOCITY"
                  : "PLATZ 1\nVELOCITY"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__esRp1)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__gy4Ds)}
              color={"blue" as const}
              link={"https://papermc.io/downloads#Velocity" as const}
              shape={"rounded" as const}
              showStartIcon={true}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg__hj0R)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nbr1C
                )}
              >
                {"DOWNLOADEN"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button___7Iea2)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jqh4
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PLATZ 2\nWATERFALL"
                  : "PLATZ 2\nWATERFALL"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__aHuMb)}
              color={"blue" as const}
              link={"https://papermc.io/downloads#Waterfall" as const}
              shape={"rounded" as const}
              showStartIcon={true}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg___54Seb)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__olHti
                )}
              >
                {"DOWNLOADEN"}
              </div>
            </Button>
          </Reveal>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMcserverProxy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMcserverProxy__VariantsArgs;
    args?: PlasmicMcserverProxy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMcserverProxy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMcserverProxy__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMcserverProxy__ArgProps,
          internalVariantPropNames: PlasmicMcserverProxy__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMcserverProxy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMcserverProxy";
  } else {
    func.displayName = `PlasmicMcserverProxy.${nodeName}`;
  }
  return func;
}

export const PlasmicMcserverProxy = Object.assign(
  // Top-level PlasmicMcserverProxy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMcserverProxy
    internalVariantProps: PlasmicMcserverProxy__VariantProps,
    internalArgProps: PlasmicMcserverProxy__ArgProps
  }
);

export default PlasmicMcserverProxy;
/* prettier-ignore-end */
