// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: 0n0Rs_PNMQ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component
import { Iframe } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: CMDBvOhaI4s/codeComponent

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicZimmerSchildWait.module.css"; // plasmic-import: 0n0Rs_PNMQ/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon

export type PlasmicZimmerSchildWait__VariantMembers = {};

export type PlasmicZimmerSchildWait__VariantsArgs = {};
type VariantPropType = keyof PlasmicZimmerSchildWait__VariantsArgs;
export const PlasmicZimmerSchildWait__VariantProps =
  new Array<VariantPropType>();

export type PlasmicZimmerSchildWait__ArgsType = {};
type ArgPropType = keyof PlasmicZimmerSchildWait__ArgsType;
export const PlasmicZimmerSchildWait__ArgProps = new Array<ArgPropType>();

export type PlasmicZimmerSchildWait__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  rufen?: p.Flex<typeof Button>;
  text?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  titletext3?: p.Flex<"h1">;
  titletext2?: p.Flex<"h1">;
  iframe?: p.Flex<typeof Iframe>;
};

export interface DefaultZimmerSchildWaitProps {}

function PlasmicZimmerSchildWait__RenderFunc(props: {
  variants: PlasmicZimmerSchildWait__VariantsArgs;
  args: PlasmicZimmerSchildWait__ArgsType;
  overrides: PlasmicZimmerSchildWait__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <title key="title">{"WARTE"}</title>

        <meta key="og:title" property="og:title" content={"WARTE"} />

        <meta key="twitter:title" name="twitter:title" content={"WARTE"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__zPqK9
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 600 }}
                  >
                    {"BITTE WARTEN..."}
                  </span>
                  <React.Fragment>{"\nDRÜCKEN SIE WEITER"}</React.Fragment>
                </React.Fragment>
              ) : (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 600 }}
                  >
                    {"BITTE WARTEN..."}
                  </span>
                  <React.Fragment>{"\nDRÜCKEN SIE WEITER"}</React.Fragment>
                </React.Fragment>
              )}
            </h2>

            {true ? (
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__mW8Ck
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 600 }}
                    >
                      {"ROBERTS ZIMMER"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 600 }}
                    >
                      {"ROBERTS ZIMMER"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                )}
              </h2>
            ) : null}

            <Button
              data-plasmic-name={"rufen"}
              data-plasmic-override={overrides.rufen}
              className={classNames("__wab_instance", sty.rufen)}
              link={"/ZIMMER-schild-d-Adg7a" as const}
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__m4HuM
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "WEITER"
                          : "OK"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__njqfs
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "OK"
                          : "WEITER"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                )}
              </div>
            </Button>
          </div>

          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <p.PlasmicLink
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("/" as const)
                  : ("/" as const)
              }
              platform={"nextjs"}
            >
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <h1
                  data-plasmic-name={"titletext3"}
                  data-plasmic-override={overrides.titletext3}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.titletext3
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "PAPERSTUDIOS"
                    : "PAPERSTUDIOS"}
                </h1>
              ) : null}

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <h1
                  data-plasmic-name={"titletext2"}
                  data-plasmic-override={overrides.titletext2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.titletext2
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "PAPERSTUDIOS"
                    : "PAPERSTUDIOS"}
                </h1>
              ) : null}
            </p.PlasmicLink>
          ) : null}

          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <Iframe
              data-plasmic-name={"iframe"}
              data-plasmic-override={overrides.iframe}
              className={classNames("__wab_instance", sty.iframe)}
              src={
                "https://trigger.macrodroid.com/1b165847-b4c4-4e84-8d44-c379588b70f7/ZIMMER-RUFER" as const
              }
            />
          ) : null}
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "rufen",
    "text",
    "link",
    "titletext3",
    "titletext2",
    "iframe"
  ],
  freeBox: ["freeBox", "rufen", "text"],
  rufen: ["rufen", "text"],
  text: ["text"],
  link: ["link", "titletext3", "titletext2"],
  titletext3: ["titletext3"],
  titletext2: ["titletext2"],
  iframe: ["iframe"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  rufen: typeof Button;
  text: "div";
  link: "a";
  titletext3: "h1";
  titletext2: "h1";
  iframe: typeof Iframe;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicZimmerSchildWait__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicZimmerSchildWait__VariantsArgs;
    args?: PlasmicZimmerSchildWait__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicZimmerSchildWait__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicZimmerSchildWait__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicZimmerSchildWait__ArgProps,
          internalVariantPropNames: PlasmicZimmerSchildWait__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicZimmerSchildWait__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicZimmerSchildWait";
  } else {
    func.displayName = `PlasmicZimmerSchildWait.${nodeName}`;
  }
  return func;
}

export const PlasmicZimmerSchildWait = Object.assign(
  // Top-level PlasmicZimmerSchildWait renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    rufen: makeNodeComponent("rufen"),
    text: makeNodeComponent("text"),
    link: makeNodeComponent("link"),
    titletext3: makeNodeComponent("titletext3"),
    titletext2: makeNodeComponent("titletext2"),
    iframe: makeNodeComponent("iframe"),

    // Metadata about props expected for PlasmicZimmerSchildWait
    internalVariantProps: PlasmicZimmerSchildWait__VariantProps,
    internalArgProps: PlasmicZimmerSchildWait__ArgProps
  }
);

export default PlasmicZimmerSchildWait;
/* prettier-ignore-end */
