// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: hglMEIPeKot
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicMcserverListe.module.css"; // plasmic-import: hglMEIPeKot/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon
import DownloadIcon143099SvgIcon from "./icons/PlasmicIcon__DownloadIcon143099Svg"; // plasmic-import: -1dlLAmHP/icon

export type PlasmicMcserverListe__VariantMembers = {};

export type PlasmicMcserverListe__VariantsArgs = {};
type VariantPropType = keyof PlasmicMcserverListe__VariantsArgs;
export const PlasmicMcserverListe__VariantProps = new Array<VariantPropType>();

export type PlasmicMcserverListe__ArgsType = {};
type ArgPropType = keyof PlasmicMcserverListe__ArgsType;
export const PlasmicMcserverListe__ArgProps = new Array<ArgPropType>();

export type PlasmicMcserverListe__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMcserverListeProps {}

function PlasmicMcserverListe__RenderFunc(props: {
  variants: PlasmicMcserverListe__VariantsArgs;
  args: PlasmicMcserverListe__ArgsType;
  overrides: PlasmicMcserverListe__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <title key="title">{"MINECRAFT SERVER"}</title>

        <meta key="og:title" property="og:title" content={"MINECRAFT SERVER"} />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={"MINECRAFT SERVER"}
        />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal__ea7Rm)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button___7UkT8)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("blue" as const)
                  : ("blue" as const)
              }
              link={"/" as const}
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3XyT
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__e2WBm)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__qfvNo)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lrvgi
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "NORMALE\nSERVER"
                  : "FÜR NORMALE SERVER\n[VANILLA/PLUGINS]"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal___0LO7H)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__y1IhM)}
              color={"blue" as const}
              link={"/serversoftware-normaler" as const}
              shape={"rounded" as const}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg__bVgf)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cvqgH
                )}
              >
                {"ANSCHAUEN"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__hUhLl)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xzuc
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "MODDED\nSERVER"
                  : "FÜR MODDED SERVER\n[VANILLA/MODS]"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button___0RSle)}
              color={"blue" as const}
              link={"/serversoftware-modded" as const}
              shape={"rounded" as const}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg__y4Dka)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ma0Gb
                )}
              >
                {"ANSCHAUEN"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button___7Iea2)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qqhHh
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PROXY\nSERVER"
                  : "FÜR PROXY SERVER\n[BUNGEECORD]"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__aHuMb)}
              color={"blue" as const}
              link={"/serversoftware-proxy" as const}
              shape={"rounded" as const}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg__er65W)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pYpfc
                )}
              >
                {"ANSCHAUEN"}
              </div>
            </Button>
          </Reveal>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMcserverListe__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMcserverListe__VariantsArgs;
    args?: PlasmicMcserverListe__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMcserverListe__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMcserverListe__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMcserverListe__ArgProps,
          internalVariantPropNames: PlasmicMcserverListe__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMcserverListe__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMcserverListe";
  } else {
    func.displayName = `PlasmicMcserverListe.${nodeName}`;
  }
  return func;
}

export const PlasmicMcserverListe = Object.assign(
  // Top-level PlasmicMcserverListe renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMcserverListe
    internalVariantProps: PlasmicMcserverListe__VariantProps,
    internalArgProps: PlasmicMcserverListe__ArgProps
  }
);

export default PlasmicMcserverListe;
/* prettier-ignore-end */
