// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: MEOYEA23cnv
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicMcserverNormaler.module.css"; // plasmic-import: MEOYEA23cnv/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon
import DownloadIcon143099SvgIcon from "./icons/PlasmicIcon__DownloadIcon143099Svg"; // plasmic-import: -1dlLAmHP/icon

export type PlasmicMcserverNormaler__VariantMembers = {};

export type PlasmicMcserverNormaler__VariantsArgs = {};
type VariantPropType = keyof PlasmicMcserverNormaler__VariantsArgs;
export const PlasmicMcserverNormaler__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMcserverNormaler__ArgsType = {};
type ArgPropType = keyof PlasmicMcserverNormaler__ArgsType;
export const PlasmicMcserverNormaler__ArgProps = new Array<ArgPropType>();

export type PlasmicMcserverNormaler__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMcserverNormalerProps {}

function PlasmicMcserverNormaler__RenderFunc(props: {
  variants: PlasmicMcserverNormaler__VariantsArgs;
  args: PlasmicMcserverNormaler__ArgsType;
  overrides: PlasmicMcserverNormaler__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <title key="title">{"NORMALER SERVER"}</title>

        <meta key="og:title" property="og:title" content={"NORMALER SERVER"} />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={"NORMALER SERVER"}
        />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal___3CidD)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__au7Ts)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("blue" as const)
                  : ("blue" as const)
              }
              link={"/" as const}
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mLjJm
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__nImEd)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__xytyJ)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o1B0T
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PLATZ 1\n0xBUKKIT"
                  : "PLATZ 1\n0xBUKKIT"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__xqMwF)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__qObbb)}
              color={"blue" as const}
              link={"https://jenkins.rjansen.de/job/0xBUKKIT" as const}
              shape={"rounded" as const}
              showStartIcon={true}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg__hKs59)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eohlp
                )}
              >
                {"DOWNLOADEN"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button___7Iea2)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uinyQ
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PLATZ 2\nPAPERMC"
                  : "PLATZ 2\nPAPERMC"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__aHuMb)}
              color={"blue" as const}
              link={
                "https://papermc.io/api/v1/paper/1.19/latest/download" as const
              }
              shape={"rounded" as const}
              showStartIcon={true}
              startIcon={
                <DownloadIcon143099SvgIcon
                  className={classNames(projectcss.all, sty.svg___6PI8)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7THla
                )}
              >
                {"DOWNLOADEN"}
              </div>
            </Button>
          </Reveal>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMcserverNormaler__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMcserverNormaler__VariantsArgs;
    args?: PlasmicMcserverNormaler__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMcserverNormaler__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMcserverNormaler__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMcserverNormaler__ArgProps,
          internalVariantPropNames: PlasmicMcserverNormaler__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMcserverNormaler__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMcserverNormaler";
  } else {
    func.displayName = `PlasmicMcserverNormaler.${nodeName}`;
  }
  return func;
}

export const PlasmicMcserverNormaler = Object.assign(
  // Top-level PlasmicMcserverNormaler renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMcserverNormaler
    internalVariantProps: PlasmicMcserverNormaler__VariantProps,
    internalArgProps: PlasmicMcserverNormaler__ArgProps
  }
);

export default PlasmicMcserverNormaler;
/* prettier-ignore-end */
