// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: mctcH_Q0eRy
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicProjekteSpieleHandy.module.css"; // plasmic-import: mctcH_Q0eRy/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon

export type PlasmicProjekteSpieleHandy__VariantMembers = {};

export type PlasmicProjekteSpieleHandy__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjekteSpieleHandy__VariantsArgs;
export const PlasmicProjekteSpieleHandy__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjekteSpieleHandy__ArgsType = {};
type ArgPropType = keyof PlasmicProjekteSpieleHandy__ArgsType;
export const PlasmicProjekteSpieleHandy__ArgProps = new Array<ArgPropType>();

export type PlasmicProjekteSpieleHandy__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultProjekteSpieleHandyProps {}

function PlasmicProjekteSpieleHandy__RenderFunc(props: {
  variants: PlasmicProjekteSpieleHandy__VariantsArgs;
  args: PlasmicProjekteSpieleHandy__ArgsType;
  overrides: PlasmicProjekteSpieleHandy__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <title key="title">{"SPIELE"}</title>

        <meta key="og:title" property="og:title" content={"SPIELE"} />

        <meta key="twitter:title" name="twitter:title" content={"SPIELE"} />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://site-assets.plasmic.app/19f123fbbe57c71668b4e38fd642f865.png"
          }
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://site-assets.plasmic.app/19f123fbbe57c71668b4e38fd642f865.png"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal___1D2LO)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button___41Z0K)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("blue" as const)
                  : ("blue" as const)
              }
              link={"/" as const}
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uu8A
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__uCyd5)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__trN9G)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__s3UbQ
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "MMC\nSPIEL [CATRO]"
                  : "MMC\nSPIEL [CATRO]"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__w7YKh)}
              color={"blue" as const}
              link={"/mmc" as const}
              shape={"rounded" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__km2Or
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "ANSCHAUEN"
                  : "ANSCHAUEN"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__iFUzc)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9FkHk
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "TAPTAP\nSPIEL [APK]"
                  : "TAPTAP\nSPIEL [APK]"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__wAs4I)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__xOwJv)}
              color={"blue" as const}
              link={"/taptap" as const}
              shape={"rounded" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__grKTj
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "ANSCHAUEN"
                  : "ANSCHAUEN"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__x4Oib)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__a3Xha)}
              color={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("green" as const)
                  : ("green" as const)
              }
              link={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("" as const)
                  : ("" as const)
              }
              shape={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("rounded" as const)
                  : ("rounded" as const)
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__glwis
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "YTBER SIM\nSPIEL [APK]"
                  : "YOUTUBER TYCOON\nSPIEL [APK]"}
              </div>
            </Button>
          </Reveal>

          <Reveal
            className={classNames("__wab_instance", sty.reveal__iwVhc)}
            triggerOnce={true}
          >
            <Button
              className={classNames("__wab_instance", sty.button__zwsSq)}
              color={"blue" as const}
              link={"/youtubertycoon" as const}
              shape={"rounded" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4Fby
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "ANSCHAUEN"
                  : "ANSCHAUEN"}
              </div>
            </Button>
          </Reveal>

          <Button
            className={classNames("__wab_instance", sty.button__oRF)}
            color={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ("green" as const)
                : ("green" as const)
            }
            link={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ("" as const)
                : ("" as const)
            }
            shape={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ("rounded" as const)
                : ("rounded" as const)
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vpvJa
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "MONEY RUSH\nSPIEL [APK]"
                : "MONEY RUSH\nSPIEL [APK]"}
            </div>
          </Button>

          <Button
            className={classNames("__wab_instance", sty.button__xF8CA)}
            color={"blue" as const}
            link={"/moneyrush" as const}
            shape={"rounded" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hbCvW
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "ANSCHAUEN"
                : "ANSCHAUEN"}
            </div>
          </Button>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjekteSpieleHandy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjekteSpieleHandy__VariantsArgs;
    args?: PlasmicProjekteSpieleHandy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjekteSpieleHandy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProjekteSpieleHandy__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProjekteSpieleHandy__ArgProps,
          internalVariantPropNames: PlasmicProjekteSpieleHandy__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProjekteSpieleHandy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjekteSpieleHandy";
  } else {
    func.displayName = `PlasmicProjekteSpieleHandy.${nodeName}`;
  }
  return func;
}

export const PlasmicProjekteSpieleHandy = Object.assign(
  // Top-level PlasmicProjekteSpieleHandy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProjekteSpieleHandy
    internalVariantProps: PlasmicProjekteSpieleHandy__VariantProps,
    internalArgProps: PlasmicProjekteSpieleHandy__ArgProps
  }
);

export default PlasmicProjekteSpieleHandy;
/* prettier-ignore-end */
