// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kNn551YTznMMb4YQ5Km9SL
// Component: W5WKNW8cZx
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 7xNG3XR7jCb/component

import { useScreenVariants as useScreenVariantstMxE3T6K3HVTc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tMxE3T6K3hVTc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_paperstudios.module.css"; // plasmic-import: kNn551YTznMMb4YQ5Km9SL/projectcss
import sty from "./PlasmicZerotierTut2.module.css"; // plasmic-import: W5WKNW8cZx/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: iG22nYJYy3C/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 45mhSrhfGtS/icon

export type PlasmicZerotierTut2__VariantMembers = {};

export type PlasmicZerotierTut2__VariantsArgs = {};
type VariantPropType = keyof PlasmicZerotierTut2__VariantsArgs;
export const PlasmicZerotierTut2__VariantProps = new Array<VariantPropType>();

export type PlasmicZerotierTut2__ArgsType = {};
type ArgPropType = keyof PlasmicZerotierTut2__ArgsType;
export const PlasmicZerotierTut2__ArgProps = new Array<ArgPropType>();

export type PlasmicZerotierTut2__OverridesType = {
  root?: p.Flex<"div">;
  googleDrive?: p.Flex<typeof Button>;
  h2?: p.Flex<"h2">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  titletext3?: p.Flex<"h1">;
  titletext2?: p.Flex<"h1">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultZerotierTut2Props {}

function PlasmicZerotierTut2__RenderFunc(props: {
  variants: PlasmicZerotierTut2__VariantsArgs;
  args: PlasmicZerotierTut2__ArgsType;
  overrides: PlasmicZerotierTut2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstMxE3T6K3HVTc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <title key="title">{"ZEROTIER TUTORIAL"}</title>

        <meta
          key="og:title"
          property="og:title"
          content={"ZEROTIER TUTORIAL"}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={"ZEROTIER TUTORIAL"}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Button
            data-plasmic-name={"googleDrive"}
            data-plasmic-override={overrides.googleDrive}
            className={classNames("__wab_instance", sty.googleDrive)}
            color={"blue" as const}
            link={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ("/" as const)
                : ("/ZROTIER-gdiwz24-3" as const)
            }
            shape={"rounded" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pVcse
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "OK"
                        : "NÄCHSTES"}
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              ) : (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "OK"
                        : "NÄCHSTES"}
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              )}
            </div>
          </Button>

          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.all, projectcss.a, sty.link)}
            component={Link}
            href={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ("/" as const)
                : ("/" as const)
            }
            platform={"nextjs"}
          >
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <h1
                data-plasmic-name={"titletext3"}
                data-plasmic-override={overrides.titletext3}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.titletext3
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </h1>
            ) : null}

            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <h1
                data-plasmic-name={"titletext2"}
                data-plasmic-override={overrides.titletext2}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.titletext2
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "PAPERSTUDIOS"
                  : "PAPERSTUDIOS"}
              </h1>
            ) : null}
          </p.PlasmicLink>

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ceuuo
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                "Dieses Programm funktioniert nur richtig auf Windows"
              ) : (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 900 }}
                  >
                    {
                      "Klicke unten rechts in Windows auf einen Pfeil der nach oben zeigt und rechtsklick auf das ZeroTierOne Icon und Öffne das Control Panel"
                    }
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              )}
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gu2Hg
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ fontWeight: 900 }}
              >
                {"2."}
              </span>
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "googleDrive",
    "h2",
    "link",
    "titletext3",
    "titletext2",
    "freeBox"
  ],
  googleDrive: ["googleDrive", "h2"],
  h2: ["h2"],
  link: ["link", "titletext3", "titletext2"],
  titletext3: ["titletext3"],
  titletext2: ["titletext2"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  googleDrive: typeof Button;
  h2: "h2";
  link: "a";
  titletext3: "h1";
  titletext2: "h1";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicZerotierTut2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicZerotierTut2__VariantsArgs;
    args?: PlasmicZerotierTut2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicZerotierTut2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicZerotierTut2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicZerotierTut2__ArgProps,
          internalVariantPropNames: PlasmicZerotierTut2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicZerotierTut2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicZerotierTut2";
  } else {
    func.displayName = `PlasmicZerotierTut2.${nodeName}`;
  }
  return func;
}

export const PlasmicZerotierTut2 = Object.assign(
  // Top-level PlasmicZerotierTut2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    googleDrive: makeNodeComponent("googleDrive"),
    h2: makeNodeComponent("h2"),
    link: makeNodeComponent("link"),
    titletext3: makeNodeComponent("titletext3"),
    titletext2: makeNodeComponent("titletext2"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicZerotierTut2
    internalVariantProps: PlasmicZerotierTut2__VariantProps,
    internalArgProps: PlasmicZerotierTut2__ArgProps
  }
);

export default PlasmicZerotierTut2;
/* prettier-ignore-end */
